### ISSUE TITLE
I'm having problems to open the py files

### ISSUE THREAD

**Issue by zzz1337-sys** [tot0k/pixelCanvasBot#3]
When I open the files, the dos close

![screenshot_2](https://user-images.githubusercontent.com/29678843/27510217-5bc12008-58e2-11e7-9c69-d4a86eef12a1.png)

Sorry, my english isn't good, and I don't understand py files

**Comment by tot0k** [comment]
You must install all the packages imported at the begining of the file.
go to https://pypi.python.org/pypi/pip and install pip for windows.
After that, you must open a cmd and type "pip install requests", wait for intallation, then "pip install addict"
If the command "pip" does not work with windows, you go to the Python instll directory, in /scripts, and you open a cmd here (shift + right clic in the window directory, then 'open cmd here'). And you time 'pip.exe install requests' and 'pip.exe install addict'
good luck :)
The server is currently configured to create a Jean Reno head at the coordinates 250 2500

**Comment by zzz1337-sys** [comment]
Well, I did it, but I can't find my fingerprint :/

**Comment by tot0k** [comment]
go on pixelCanvas.io, open the element analyser (f12) and go to network. place a pixel, and click on the "pixel" line. Go to the bottom, and you have your fingerprint
![image](https://user-images.githubusercontent.com/13762778/27510526-caeb979e-5912-11e7-8aef-30ea423f04f8.png)

**Comment by zzz1337-sys** [comment]
It's works! Thank u so much. One tip, can u do a bot with proxy?

**Comment by tot0k** [comment]
No, I can't do that.
